# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 01:37
from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

POSTS = [
    {
        "title": "Django 1.0 Release",
        "slug": "django-10-released",
        "pub_date": date(2008, 9, 3),
        "startups": [],
        "tags": ["django", "python", "web"],
        "text": "THE Web Framework.",
    },
]


def add_post_data(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Startup = apps.get_model(
        'organizer', 'Startup')
    Tag = apps.get_model('organizer', 'Tag')
    for post_dict in POSTS:
        post = Post.objects.create(
            title=post_dict['title'],
            slug=post_dict['slug'],
            text=post_dict['text'])
        post.pub_date = post_dict['pub_date']
        post.save()
        for tag_slug in post_dict['tags']:
            post.tags.add(
                Tag.objects.get(
                    slug=tag_slug))
        for startup_slug in post_dict['startups']:
            post.startups.add(
                Startup.objects.get(
                    slug=startup_slug))


def remove_post_data(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post_dict in POSTS:
        post = Post.objects.get(
            slug=post_dict['slug'])
        post.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
	('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
