# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
	migrations.AlterUniqueTogether(
		name='newslink',
		unique_together=set([('slug', 'startup')]),),
    ]
